---
# JMX Exporter Configuration for Kafka
lowercaseOutputName: true
lowercaseOutputLabelNames: true

# Whitelist of JMX MBean patterns to scrape
whitelistObjectNames:
  - "kafka.server:*"
  - "kafka.network:*"
  - "kafka.log:*"
  - "kafka.controller:*"
  - "kafka.cluster:*"
  - "java.lang:*"

# Rules to transform JMX metrics to Prometheus format
rules:
  # Broker metrics
  - pattern: kafka.server<type=(.+), name=(.+)><>Value
    name: kafka_server_$1_$2
    type: GAUGE
    
  # Network metrics
  - pattern: kafka.network<type=(.+), name=(.+)><>Value
    name: kafka_network_$1_$2
    type: GAUGE
    
  # Log metrics
  - pattern: kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value
    name: kafka_log_$1
    type: GAUGE
    labels:
      topic: "$2"
      partition: "$3"
      
  # Controller metrics
  - pattern: kafka.controller<type=(.+), name=(.+)><>Value
    name: kafka_controller_$1_$2
    type: GAUGE
    
  # JVM metrics
  - pattern: "java.lang<type=Memory><HeapMemoryUsage>used"
    name: jvm_memory_heap_used
    type: GAUGE
    
  - pattern: "java.lang<type=Memory><HeapMemoryUsage>max"
    name: jvm_memory_heap_max
    type: GAUGE
    
  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionCount"
    name: jvm_gc_collection_count
    type: COUNTER
    labels:
      gc: "$1"
      
  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionTime"
    name: jvm_gc_collection_time_ms
    type: COUNTER
    labels:
      gc: "$1"
